Fix hash ncube + add plotting utilities
pyccel/sympde pull request #112
Opened 2022-07-21 12:02 UTC by anlavandier

2022-07-21 14:43 UTC, yguclu commented
Thanks for this PR! Can you please provide a short summary of the changes made?

2022-07-21 14:49 UTC, anlavandier commented
I updated the main comment.

2022-07-21 17:36 UTC, yguclu requested changes
Good job! I have a couple of request regarding file `sympde.utilities/utils.py`:

- Please add some docstrings to the new functions 
- Given that it is not convenient to add unit tests for visualization functions, please add a short example of usage, which can be included at the bottom of the file under the section `if __name__ == '__main__':`

2022-07-21 17:36 UTC, yguclu commented on sympde/utilities/utils.py
> +    ax.plot(XX[::5, :].T, YY[::5, :].T, 'k')
No newline at end of file

2022-07-22 12:14 UTC, yguclu requested changes
Please add labels to the `x`, `y`, and `z` axes.

2022-07-22 12:42 UTC, yguclu requested changes

2022-07-22 12:42 UTC, yguclu commented on sympde/utilities/utils.py
> +    refinement : int, default=15
Please add "Number of straight line segments used to approximate each boundary edge."

2022-07-22 12:42 UTC, yguclu commented on sympde/utilities/utils.py
> +    refinement : int, default=40
See above

2022-07-22 12:46 UTC, anlavandier commented on sympde/utilities/utils.py
> +    refinement : int, default=15
Done in [825c1fa](https://github.com/pyccel/sympde/pull/112/commits/825c1fa5adee918fbc3b8f56eb501853705865a2)

2022-07-22 12:46 UTC, anlavandier commented on sympde/utilities/utils.py
> +    refinement : int, default=40
Done in [825c1fa](https://github.com/pyccel/sympde/pull/112/commits/825c1fa5adee918fbc3b8f56eb501853705865a2)

2022-07-22 12:51 UTC, yguclu approved these changes

2022-07-22 12:55 UTC, merged