new join method
pyccel/sympde pull request #130
Opened 2023-06-20 01:09 UTC by saidctb

2023-06-20 07:38 UTC, yguclu commented
Does this PR solve issue #108?

2023-06-20 10:09 UTC, saidctb commented
> Does this PR solve issue #108?

yes

2023-06-20 10:12 UTC, yguclu commented
> > Does this PR solve issue #108?
> 
> yes

That's great! Please add a short description to this PR.

2023-06-22 07:17 UTC, yguclu reviewed
This looks very good @saidctb!

Could you add an example/test in 3D?

Further, have you checked if we are now able to connect two patches with more than one interface?

2023-06-22 13:14 UTC, saidctb commented
> This looks very good @saidctb!
> 
> Could you add an example/test in 3D?
> 
> Further, have you checked if we are now able to connect two patches with more than one interface?

the 3D test was added in [bb148fe](https://github.com/pyccel/sympde/pull/130/commits/bb148fe335e1f62f7cfef7d3904791ff37517079)

2023-06-23 09:36 UTC, yguclu requested changes
Great job @saidctb!

I have some minor comments.

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    print(domain)
Can we add an `assert` statement of some sort here?

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    print(domain)
Can we add an `assert` statement of some sort here?

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/domain.py
> +                boundaries.append(bnd_plus)
You can remove the `if/elif` blocks and compute `ornt` based on the dimension. The rest of the code is identical for all cases.

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    connectivity = [((0, 0, 1),(1, 0, -1)),((1,0,1),(2,0,-1))]
More readable:
```suggestion
    connectivity = [((0, 0, 1), (1, 0, -1)), ((1, 0, 1), (2, 0, -1))]
```

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +                    ((3,1,1),(2,1,-1))]
More readable
```suggestion
    connectivity = [((0, 0, 1), (2, 0,-1)),
                    ((1, 0, 1), (3, 0,-1)),
                    ((2, 0, 1), (0, 0,-1)),
                    ((3, 0, 1), (1, 0,-1)),
                    ((0, 1, 1), (1, 1,-1)),
                    ((2, 1, 1), (3, 1,-1)),
                    ((1, 1, 1), (0, 1,-1)),
                    ((3, 1, 1), (2, 1,-1))]
```

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    connectivity = [((0, 0, 1),(1, 0, -1)),((1,0,1),(2,0,-1))]
More readable:
```suggestion
    connectivity = [((0, 0, 1),(1, 0, -1)), ((1, 0, 1), (2, 0, -1))]
```

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    connectivity = [((0, 0, 1),(1, 0, -1))]
More readable:
```suggestion
    connectivity = [((0, 0, 1), (1, 0, -1))]
```

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    connectivity = [((0, 0, 1),(1, 0, -1)),((1,0,1),(2,0,-1))]
More readable:
```suggestion
    connectivity = [((0, 0, 1), (1, 0, -1)), ((1, 0, 1), (2, 0, -1))]
```

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    connectivity = [((0, 0, 1),(1, 0, -1))]
More readable:
```suggestion
    connectivity = [((0, 0, 1), (1, 0, -1))]
```

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    connectivity = [((0, 0, 1),(1, 0, -1))]
More readable:
```suggestion
    connectivity = [((0, 0, 1), (1, 0, -1))]
```

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    assert ABC.interfaces == Union(Interface('A|B', AB_bnd_minus, AB_bnd_plus,ornt=1),Interface('B|C', BC_bnd_minus, BC_bnd_plus,ornt=1))
More readable:
```suggestion
    assert ABC.interfaces == Union(Interface('A|B', AB_bnd_minus, AB_bnd_plus, ornt=1),
                                   Interface('B|C', BC_bnd_minus, BC_bnd_plus, ornt=1))
```

2023-06-23 09:36 UTC, yguclu commented on sympde/topology/tests/test_topology.py
> +    connectivity = [((0, 0, 1),(1, 0, -1))]
More readable:
```suggestion
    connectivity = [((0, 0, 1), (1, 0, -1))]
```

2023-06-23 12:53 UTC, saidctb commented on sympde/topology/domain.py
> +                boundaries.append(bnd_plus)
fixed in [e700a39](https://github.com/pyccel/sympde/pull/130/commits/e700a39e502a080f7c403e041640a96c0794bae9)

2023-06-23 12:53 UTC, saidctb commented on sympde/topology/tests/test_topology.py
> +    print(domain)
done in [e700a39](https://github.com/pyccel/sympde/pull/130/commits/e700a39e502a080f7c403e041640a96c0794bae9)

2023-06-23 12:54 UTC, saidctb commented on sympde/topology/tests/test_topology.py
> +    print(domain)
done in [e700a39](https://github.com/pyccel/sympde/pull/130/commits/e700a39e502a080f7c403e041640a96c0794bae9)

2023-06-26 18:11 UTC, yguclu approved these changes

2023-06-26 18:23 UTC, merged