Add logical operators
pyccel/sympde pull request #71
Opened 2020-06-21 14:25 UTC by saidctb

2020-08-05 15:12 UTC, yguclu commented on sympde/calculus/matrices.py
> +class MatrixSymbolicExpr(Expr):
This class looks very well done. But why not using `MatrixSymbol` and `MatrixExpr` from `sympy.matrices.expressions`? See https://docs.sympy.org/latest/modules/matrices/expressions.html#sympy.matrices.expressions.MatrixExpr

2020-08-05 15:52 UTC, yguclu commented on sympde/calculus/matrices.py
> +        return SymbolicDeterminant(self)
The determinant does not exist for non-square matrices. Do we make this check somewhere?

2020-08-05 16:02 UTC, yguclu commented on sympde/exterior/tests/test_compiler.py
>  def test_compiler_3d_1():
Why is this test failing now?

2020-08-05 16:11 UTC, yguclu commented on sympde/expr/evaluation.py
> +                #terminal_expr = expand(terminal_expr)
We do not need these operations anymore?

2020-08-06 05:33 UTC, saidctb commented on sympde/calculus/matrices.py
> +class MatrixSymbolicExpr(Expr):
it can work if all our nodes inherits from `MatrixSymbol`  like `grad, curl, rot, VectorTestFunction, cross, ...`
we also need to add many methods and attributes to our nodes so that an operation like `A*u` will be valid and will not crash in `Sympy`

2020-08-06 05:35 UTC, saidctb commented on sympde/calculus/matrices.py
> +        return SymbolicDeterminant(self)
here we don't have any information about the shape so we can't check , but it will crash in `TerminalExpr` if it's not square

2020-08-06 05:47 UTC, saidctb commented on sympde/expr/evaluation.py
> +                #terminal_expr = expand(terminal_expr)
I'm not sure yet,  I deleted the `DetJacobian(mapping)` and `SymbolicDeterminant(mapping)`  bacause we don't need them anymore, the problem is I don't know how `TensorExpr` suppose to work especially that it is used in `gelato` and`psydac` so I prefer to keep those lines as comments

2020-08-06 05:48 UTC, saidctb commented on sympde/calculus/matrices.py
> +class MatrixSymbolicExpr(Expr):
also some methods are not yet implemented in `MatrixSymbol`  like `__abs__`  so `abs(A)` will crash

2020-08-06 06:27 UTC, saidctb commented on sympde/exterior/tests/test_compiler.py
>  def test_compiler_3d_1():
it is passing now

2020-08-06 07:29 UTC, yguclu commented on sympde/calculus/matrices.py
> +        return MatMul(self , other**S.NegativeOne)
Shouldn't we use Pow here, as in line 73?

2020-08-06 07:32 UTC, yguclu commented on sympde/calculus/matrices.py
> +class MatrixSymbolicExpr(Expr):
Do you think we should move to `MatrixSymbol` in the future? It looks natural to leverage Sympy's classes as much as possible in SymPDE...

2020-08-06 07:33 UTC, yguclu commented on sympde/calculus/matrices.py
> +        return SymbolicDeterminant(self)
Very good!

2020-08-06 08:03 UTC, yguclu commented on sympde/topology/derivatives.py
> +            v = (log(b)*cls(e, evaluate=True) + e*cls(b, evaluate=True)/b) * b**e
So `cls.eval(e)` does not work here and one should use `cls(e, evaluate=True)` instead? Can you explain why?

2020-08-06 08:12 UTC, yguclu commented on sympde/topology/derivatives.py
> +@cacheit
I think you can only use the `@cacheit` decorator on functions that return **immutable** objects. This one returns a list, so this is a potential bug. See https://github.com/sympy/sympy/blob/33e01913477c9ad7c652cdce1eba6da83ee0ee37/sympy/core/cache.py#L43

2020-08-06 08:13 UTC, yguclu commented on sympde/topology/derivatives.py
> +        """."""
You either put a docstring here, or you don't and make the file shorter...

2020-08-06 08:16 UTC, saidctb commented on sympde/calculus/matrices.py
> +class MatrixSymbolicExpr(Expr):
yes if we can, it will be great

2020-08-06 08:18 UTC, saidctb commented on sympde/topology/derivatives.py
> +            v = (log(b)*cls(e, evaluate=True) + e*cls(b, evaluate=True)/b) * b**e
I forgot why I changed it , both should work in principal

2020-08-06 08:45 UTC, yguclu commented on sympde/topology/mapping.py
> +        return f
Can you explain what this `cancel` function does? And what is `parallel_poly_from_expr` doing here?

2020-08-06 08:53 UTC, yguclu commented on sympde/topology/mapping.py
> +        obj._jacobian            = kwargs.pop('jacobian', JacobianSymbol(obj))
If I understand correctly, `mapping._jacobian` is now just a symbol. Do you overwrite this attribute in the case of an analytical mapping?

2020-08-06 08:58 UTC, yguclu commented on sympde/topology/mapping.py
> +            expr  =  A*ImmutableDenseMatrix(tuple(el[i] for i in range(dim)))
Can you write this in one line, as in all the other cases? That makes it easier to read.

2020-08-06 09:01 UTC, yguclu commented on sympde/topology/mapping.py
> +            raise NotImplementedError('TODO')
I am not sure that we should raise a `NotImplementedError` here. I would rather raise a
```
ValueError("Unrecognized kind '{}' of space {}".format(kind, str(u.space)))
```

2020-08-06 09:06 UTC, yguclu commented on sympde/topology/mapping.py
>  class Covariant(MappingApplication):
This class represents the "covariant Piola transform" of a vector field, right? If so, I suggest we change its name to make it more explicit (e.g. `CovariantPiolaTransform`) As another option, you could add a nice docstring here.

2020-09-03 07:47 UTC, saidctb commented on sympde/topology/derivatives.py
> +@cacheit
yes you are right, I will fix it

2020-09-03 07:52 UTC, saidctb commented on sympde/topology/mapping.py
> +        return f
it's used to simplify fractions, and the function `parallel_poly_from_expr` is used to Construct polynomials from expressions

2020-09-03 07:52 UTC, saidctb commented on sympde/topology/mapping.py
> +        obj._jacobian            = kwargs.pop('jacobian', JacobianSymbol(obj))
no , it stays the same

2020-09-03 07:57 UTC, saidctb commented on sympde/expr/evaluation.py
> +                #terminal_expr = expand(terminal_expr)
I will delete them as they are useless now

2020-09-03 07:58 UTC, saidctb commented on sympde/calculus/matrices.py
> +        return MatMul(self , other**S.NegativeOne)
it will call Pow , so it should be fine

2020-09-03 07:58 UTC, saidctb commented on sympde/topology/derivatives.py
> +        """."""
done

2020-09-03 08:02 UTC, saidctb commented on sympde/topology/mapping.py
> +            expr  =  A*ImmutableDenseMatrix(tuple(el[i] for i in range(dim)))
done

2020-09-03 08:03 UTC, saidctb commented on sympde/topology/mapping.py
> +            raise NotImplementedError('TODO')
done

2020-09-03 08:05 UTC, saidctb commented on sympde/topology/mapping.py
>  class Covariant(MappingApplication):
no it's not the covariant Piola transform `P`, it's only the covariant matrix `A`  where `P = A*u`

2020-09-04 13:42 UTC, yguclu commented on sympde/topology/space.py
>              raise TypeError('Expecting kind to be of SpaceType')
I think the code cannot enter this branch, given the `assert` statement on line 134. If you want to raise a nice error you should remove the assert statement and explicitly check the type of `kind`.

2020-09-04 13:58 UTC, yguclu commented on sympde/topology/space.py
> +        obj._shape  = shape
It would seem natural to process `kind` first, and then pass all arguments to `Basic`:
```
kind = ...
obj = Basic.__new__(cls, name, domain, shape, kind)
```
One advantage of doing so is that there is no need to redefine the `__hash__` function. So why did you choose to attach attributes to the object after creation instead? Did you want to allow for mutable arguments?

2020-09-04 14:02 UTC, yguclu commented on sympde/topology/space.py
> +        obj._name  = name
I have a similar comment as above. Why not writing simply
```
obj = Expr.__new__(cls, space, name)
```
and avoid redefining `__hash__`?

2020-09-04 14:02 UTC, yguclu commented on sympde/topology/space.py
> +        obj._name = name
As above...

2020-09-04 14:04 UTC, yguclu commented on sympde/exterior/tests/test_compiler.py
> +    #assert(ExteriorCalculusExpr(expr) == expected)
Is this identity not working anymore?

2020-09-04 14:07 UTC, yguclu commented on sympde/calculus/tests/test_calculus.py
> +    #assert( grad(dot(F,G)) == convect(F, G) + convect(G, F) + cross(F, curl(G)) - cross(curl(F), G) )
Is there a way to verify this identity, maybe by calling `simplify`?

2020-09-04 14:09 UTC, yguclu commented on sympde/calculus/tests/test_calculus.py
> +    #assert( div(cross(F,G)) == -dot(F, curl(G)) + dot(G, curl(F)) )
As above..

2020-09-04 14:09 UTC, yguclu commented on sympde/calculus/tests/test_calculus.py
> +    #assert( curl(f*F) == f*curl(F) + cross(grad(f), F) )
As above..

2020-09-04 14:09 UTC, yguclu commented on sympde/calculus/tests/test_calculus.py
> +    #assert( laplace(f*g) == f*laplace(g) + g*laplace(f) + 2*dot(grad(f), grad(g)) )
As above..

2020-09-04 14:09 UTC, yguclu commented on sympde/calculus/tests/test_calculus.py
> +    #assert( div(f*F) == f*div(F) + dot(F, grad(f)))
As above..

2020-09-04 14:09 UTC, yguclu commented on sympde/calculus/tests/test_calculus.py
> +    #assert( curl(f*grad(g)) == cross(grad(f), grad(g)) )
As above..

2020-09-04 14:10 UTC, yguclu commented on sympde/expr/basic.py
> +            test_functions = arguments[1]
Well spotted! 👍

2020-09-04 14:11 UTC, yguclu commented on sympde/expr/basic.py
> +        trial_functions = arguments[0]
Well spotted! 👍

2020-09-04 14:12 UTC, yguclu commented on sympde/expr/basic.py
> +    args = Tuple(trial_functions, test_functions) if is_bilinear else Tuple(*test_functions)
Well spotted! 👍

2020-09-05 08:30 UTC, yguclu commented on sympde/calculus/matrices.py
> +    _op_priority   = 10.5
Are we using this new `Matrix` class now in SymPDE?
In many places I have seen `sympy.Matrix` being used instead.

2020-09-07 16:22 UTC, saidctb commented on sympde/calculus/matrices.py
> +    _op_priority   = 10.5
ah we don't need it anymore, we can use it if you want

2020-09-07 16:28 UTC, saidctb commented on sympde/topology/space.py
> +        obj._shape  = shape
Sympy always does some operations on the args of Basic, so if the args are not needed to be processed we don't inculude them in Basic espacialy if they are not Sympy types like the name is a string the shape is a tuple of integers.
a good example is the class `Symbol` of Sympy, they do the same thing https://github.com/sympy/sympy/blob/master/sympy/core/symbol.py#L265
and it's also faster, if we include the args in Basic and we call the expand method it will try to expand the args also.

2020-09-07 16:32 UTC, saidctb commented on sympde/topology/space.py
>              raise TypeError('Expecting kind to be of SpaceType')
ah yes you are right

2020-09-07 16:37 UTC, saidctb commented on sympde/exterior/tests/test_compiler.py
> +    #assert(ExteriorCalculusExpr(expr) == expected)
not anymore

2020-09-07 16:38 UTC, saidctb commented on sympde/calculus/tests/test_calculus.py
> +    #assert( grad(dot(F,G)) == convect(F, G) + convect(G, F) + cross(F, curl(G)) - cross(curl(F), G) )
yes we can add some `eval_exapnd` methods to de these kind of simplifications, but it needs more work

2020-09-10 20:27 UTC, yguclu commented on sympde/topology/space.py
> +        obj._shape  = shape
I see. Thanks for the explanation!

2020-09-10 20:28 UTC, yguclu commented on sympde/calculus/matrices.py
> +    _op_priority   = 10.5
If we don't need it, I am in favor of removing it...

2020-09-10 20:38 UTC, yguclu commented on sympde/calculus/tests/test_calculus.py
> +    #assert( grad(dot(F,G)) == convect(F, G) + convect(G, F) + cross(F, curl(G)) - cross(curl(F), G) )
Can you please create an issue where you list all the identities that are not automatically verified after this pull request?

2020-09-10 20:46 UTC, saidctb commented on sympde/topology/space.py
> +        obj._name  = name
the explanation as above

2020-09-10 20:46 UTC, saidctb commented on sympde/calculus/matrices.py
> +    _op_priority   = 10.5
okay

2020-09-14 09:34 UTC, saidctb commented on sympde/calculus/tests/test_calculus.py
> +    #assert( grad(dot(F,G)) == convect(F, G) + convect(G, F) + cross(F, curl(G)) - cross(curl(F), G) )
done

2020-09-14 13:07 UTC, yguclu commented on sympde/topology/domain.py
> +        return self._args[3]
As done above, we should use `args` instead of `_args`. See also [here](https://docs.sympy.org/latest/modules/core.html?highlight=basic#sympy.core.basic.Basic):

> Never use self._args, always use self.args. Only use _args in `__new__` when creating a new function. Don’t override .args() from Basic (so that it’s easy to change the interface in the future if needed).

2020-09-14 13:15 UTC, yguclu commented on sympde/topology/domain.py
> +import sympde
We should only import what is needed. Hence:
```python
from .mapping import Mapping, InterfaceMapping
```

2020-09-14 13:28 UTC, yguclu commented on sympde/topology/domain.py
> +                                           logical_domain=int_logical_domain)
What is the expected behavior when one boundary has a `mapping` and the other doesn't?

Here it looks like you are demoting the interface to a situation without any mappings.

For me it seems more natural to promote the boundary without a mapping to a mapped boundary with an `IdentityMapping` instead...

2020-09-14 13:32 UTC, yguclu commented on sympde/topology/domain.py
> +            logical_domain       = None
Here I have a similar comment... why not promoting any non-mapped domain to a mapped domain with `IdentityMapping`?

2020-09-14 13:51 UTC, saidctb commented on sympde/topology/domain.py
> +                                           logical_domain=int_logical_domain)
when we have an identity mapping, our domain becomes a mapped domain, so the coordinates will be in the physical coordinates , the evaluation of the mapping is in the end in `Psydac` or in LogicalExpr if you passe it the right keyword

2020-09-14 14:24 UTC, saidctb commented on sympde/topology/domain.py
> +import sympde
it's not possible because of the circular imports

2020-09-14 15:09 UTC, saidctb commented on sympde/topology/domain.py
> +            logical_domain       = None
as Above

2020-09-14 15:10 UTC, saidctb commented on sympde/topology/domain.py
> +        return self._args[3]
yes you are right

2020-09-14 15:51 UTC, yguclu commented on sympde/expr/expr.py
>              return eq
I think the case where `self.expr == a.expr` should automatically yield `self.expr - a.expr == 0`, so we could reduce this expression to
```
if isinstance(a, Integral):
    return (self.domain == a.domain) and ((self.expr - a.expr).expand() == 0)
```

2020-09-14 16:08 UTC, yguclu commented on sympde/expr/expr.py
> +        domain = _get_domain(expr)
Why did you move this instruction from its original location 5 lines below?

2020-09-14 16:24 UTC, yguclu commented on sympde/expr/expr.py
>          right_expr = right_expr.subs(arg, right)
If I remember correctly, the `subs` method accepts a dictionary (or an iterable container of `(old, new)` pairs) as an argument. Then a more efficient way to do this should be
```
left_expr  = expr.subs(zip(args, left_args ))
right_expr = expr.subs(zip(args, right_args))
```

2020-09-14 23:56 UTC, saidctb commented on sympde/expr/expr.py
>              return eq
self.expr - a.expr   will call the `__sub__` so I didn't want to call that  and check first if they are equal otherwise we need to expand both

2020-09-15 01:47 UTC, saidctb commented on sympde/expr/expr.py
> +        domain = _get_domain(expr)
no particular reason , we just need it at the end

2020-09-15 01:53 UTC, saidctb commented on sympde/expr/expr.py
>          right_expr = right_expr.subs(arg, right)
done

2020-09-15 08:44 UTC, yguclu commented on sympde/expr/evaluation.py
> +from sympde.topology       import LogicalExpr, PullBack
Could you please write down the full path to the modules?
(Unfortunately our `__init__.py` files are importing everything in the folder, we should change that in the future.)

2020-09-15 09:06 UTC, yguclu commented on sympde/expr/evaluation.py
>  from sympy import Indexed, Matrix, ImmutableDenseMatrix
Do we still use the mutable `sympy.Matrix`? I thought not.

2020-09-15 09:11 UTC, yguclu commented on sympde/expr/evaluation.py
> +            d_indices[x] = n
I suppose this is a bugfix, but I am struggling to understand what this function does and why it is needed...
Can you please add a docstring to it?

By the way, I also don't see why we need function `zero_matrix` just above: can't we just use `sympy.matrices.zeros(n_rows, n_cols)`, and eventually convert it to an `ImmutableDenseMatrix`?

2020-09-15 09:26 UTC, yguclu commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
The original function was taking a mutable matrix `M` as an input argument, and it modified it.

But now we are returning a new `ImmutableDenseMatrix`, so why do we need to get `M` as an input? In any case it seems wrong to change an input argument and return something else.

Maybe I am completely misunderstanding what this function is supposed to do. So please add a docstring to it!

2020-09-15 09:27 UTC, yguclu commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
Here I have the same comment as above

2020-09-15 09:47 UTC, yguclu commented on sympde/expr/expr.py
>              return eq
Do you think `__sub__` is slower than `__eq__` for Sympy expressions?

2020-09-15 09:49 UTC, yguclu commented on sympde/expr/expr.py
> +        domain = _get_domain(expr)
Then I would put it back to where it was. There were two lines of comments just before this line, which don't make any sense right now...

2020-09-15 09:51 UTC, saidctb commented on sympde/expr/expr.py
>              return eq
`__sub__` is gonna call our calculus operators magic methods so it will be slow for sure, but `__eq__` just tests if the args are the same and the type is the same which is faster

2020-09-15 10:06 UTC, saidctb commented on sympde/expr/evaluation.py
>  from sympy import Indexed, Matrix, ImmutableDenseMatrix
the user should not use it, not us

2020-09-15 11:12 UTC, saidctb commented on sympde/expr/evaluation.py
> +from sympde.topology       import LogicalExpr, PullBack
done

2020-09-15 11:12 UTC, saidctb commented on sympde/expr/evaluation.py
> +            d_indices[x] = n
done

2020-09-15 11:12 UTC, saidctb commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
done

2020-09-15 11:12 UTC, saidctb commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
done

2020-09-15 11:13 UTC, saidctb commented on sympde/expr/expr.py
> +        domain = _get_domain(expr)
done

2020-09-15 11:51 UTC, yguclu commented on sympde/expr/evaluation.py
> +            d_indices[x] = n
Thanks for adding the docstring! But you haven't answered by question...

2020-09-15 11:54 UTC, yguclu commented on sympde/expr/evaluation.py
> +            d_indices[x] = n
Ah OK, I see that you made the changes too.

2020-09-15 12:28 UTC, yguclu commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
So why do we need to pass `M` as an input to this function? Can't we just create a new matrix in the function?

2020-09-15 12:38 UTC, saidctb commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
this is the job of _init_matrix otherwise we will merge them

2020-09-15 13:56 UTC, yguclu commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
If `_init_matrix` is only called before one of
1. `_to_matrix_functional_form`,
2. `_to_matrix_linear_form`, or
3. `_to_matrix_bilinear_form`,

then I think it is much clearer to split the code inside `_init_matrix` into three separate parts (it already treats three different cases) to be added to the beginning of each of those functions. And then `_init_matrix` can be removed.

2020-09-15 14:02 UTC, yguclu commented on sympde/topology/domain.py
> +import sympde
Do you mean that `topology.domain` imports `topology.mapping` and vice versa?

If this is the problem, I don't think that you are implementing the correct solution to it.

2020-09-15 14:09 UTC, yguclu commented on sympde/topology/domain.py
>                   not isinstance( interiors, InteriorDomain) ):
This can be written without calling `isinstance` multiple times, while retaining the same clarity. For example
```python
iterable_types = (tuple, list, Tuple, Union)
if not isinstance(interiors, (*iterable_types, InteriorDomain)):
    ...
```
The tuple `iterable_types` could even be defined at the module level and reused in multiple places.

2020-09-15 14:45 UTC, yguclu commented on sympde/topology/domain.py
> +import sympde
Please add a comment about this circular dependency in both modules, and create a dedicated issue.

2020-09-15 15:07 UTC, saidctb commented on sympde/topology/domain.py
> +import sympde
done

2020-09-15 15:20 UTC, saidctb commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
the problem is  we don't pass `BilinearForm` or `LinearForm` to the `_to_matrix` function but rather `Integral` so we can't do the initialization there because we don't have the information

2020-09-15 15:25 UTC, saidctb commented on sympde/topology/domain.py
>                   not isinstance( interiors, InteriorDomain) ):
done

2020-09-15 15:25 UTC, yguclu commented on sympde/expr/expr.py
>              return eq
I see, thanks!

2020-09-15 15:32 UTC, yguclu commented on sympde/topology/domain.py
>                   not isinstance( interiors, InteriorDomain) ):
Can we merge these two lines? It's much easier to read:
```python
if not isinstance(interiors, (*iterable_types, InteriorDomain)):
    ...
```

2020-09-15 15:33 UTC, yguclu commented on sympde/topology/domain.py
>                   not isinstance( boundaries, Boundary) ):
As above...

By the way, is a `Union` accepted here?

2020-09-15 15:36 UTC, saidctb commented on sympde/topology/domain.py
>                   not isinstance( boundaries, Boundary) ):
done, yes it's accepted

2020-09-15 15:43 UTC, yguclu commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
The docstring that you just wrote says that `expr` is a bilinear form. Maybe it should be updated and say that it is an `Integral`?

I think all the information needed is available. `_to_matrix` is called only once, and so is `_to_matrix_form`. I can see no reason to have those functions, I think they can be removed after moving their code to the appropriate place in the module.

2020-09-15 15:48 UTC, yguclu commented on sympde/topology/mapping.py
> +        return f
Thanks! Please add a short docstring.

2020-09-15 15:54 UTC, yguclu commented on sympde/topology/mapping.py
>      """
This class is now used so extensively that it deserves a proper docstring. In particular one should explain the difference (if any) between `M.jacobian` and `Jacobian(M)`.

2020-09-15 15:58 UTC, saidctb commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
the docstring says it takes a bilinear form not  a `BilinearForm` object  which is different it actually takes a `sympy.Expr` as described in the docstring  , as for the `_to_matrix` function even though it's called once it's better to keep as it is, because it makes the code easier to read otherwise it will be more complicated than it already is

2020-09-15 16:00 UTC, yguclu commented on sympde/topology/mapping.py
>          return expr
What is the type of the returned expression? Is it a `Matrix`, an `ImmutableDenseMatrix`, a `tuple`, or something else? This should be explained in the docstring, or at least with a comment line.

2020-09-15 16:15 UTC, yguclu commented on sympde/topology/mapping.py
> +            expr =  el
Here I understand that if the user does not specify the function space we treat it as H^1, which corresponds to 0-forms. I don't think that this is the right place to put a default value, as it would be better in the space constructor. Moreover, this behavior makes little sense for vector functions.

@campospinto What do you think?

2020-09-15 16:16 UTC, yguclu commented on sympde/topology/mapping.py
>  class MappingApplication(Function):
Can you add a short docstring that explains what this class means?

2020-09-16 12:13 UTC, saidctb commented on sympde/topology/mapping.py
>          return expr
done

2020-09-16 12:13 UTC, saidctb commented on sympde/topology/mapping.py
>      """
done

2020-09-16 12:13 UTC, saidctb commented on sympde/topology/mapping.py
>  class MappingApplication(Function):
done

2020-09-16 13:38 UTC, campospinto commented on sympde/topology/mapping.py
> +            expr =  el
I agree, if a (scalar) space is seen as 'H1' by default, then that should be stored in the space attributes at construction

2020-09-16 13:40 UTC, saidctb commented on sympde/topology/mapping.py
> +            expr =  el
it's not H1 by default we have the case of the bilaplacian where it's assumed to be H2

2020-09-16 13:54 UTC, campospinto commented on sympde/topology/mapping.py
> +            expr =  el
Ok but I imagine that here, 'H1' means that it is seen as at the 'H1' position in the de Rham diagram. So if some diagram operations need to be performed on elements of the space, like pull-backs or projections, the code will select those associated with the H1 space

2020-09-16 13:56 UTC, campospinto commented on sympde/topology/mapping.py
> +            expr =  el
(and by the way, this is not incompatible with H2 : you can require an 'H1' space in the diagram to only contain H2 functions : we need to distinguish the position in the sequence and the smoothness of the functions)

2020-09-16 14:04 UTC, campospinto commented on sympde/expr/evaluation.py
>  from sympy import Indexed, Matrix, ImmutableDenseMatrix
@saidctb what do you mean ?

2020-09-16 14:08 UTC, saidctb commented on sympde/expr/evaluation.py
>  from sympy import Indexed, Matrix, ImmutableDenseMatrix
the user can only use an `ImmutableDenseMatrix`  of `sympy` when  he wants to create a vector function for example

2020-09-16 14:10 UTC, campospinto commented on sympde/topology/domain.py
> +                                           logical_domain=int_logical_domain)
@saidctb ok but if one boundary has a mapping then it means that we are in physical coordinates, so why would that be a problem for the adjacent domain ?

2020-09-16 14:17 UTC, campospinto commented on sympde/topology/domain.py
> +                                           logical_domain=int_logical_domain)
(if you are avoiding using the `IdentityMapping` to accelerate the code, would it be possible instead to switch some evaluations when the mapping is the identity ?)

2020-09-16 15:12 UTC, yguclu requested changes

2020-09-16 15:12 UTC, yguclu commented on sympde/calculus/core.py
>          """."""
Please remove this empty docstring...

2020-09-16 15:12 UTC, yguclu commented on sympde/calculus/core.py
>          """."""
Please remove this empty docstring...

2020-09-16 15:12 UTC, yguclu commented on sympde/calculus/core.py
>          """."""
Please remove this empty docstring...

2020-09-16 15:12 UTC, yguclu commented on sympde/calculus/core.py
>          """."""
Please remove this empty docstring...

2020-09-16 15:12 UTC, yguclu commented on sympde/calculus/core.py
>          """."""
Please remove this empty docstring...

2020-09-18 13:49 UTC, yguclu commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
I've just pushed a commit where I streamline the code a bit, please let me know what you think.

2020-09-21 09:19 UTC, saidctb commented on sympde/expr/evaluation.py
> +    return ImmutableDenseMatrix(M)
thanks @yguclu , it should be good

2020-09-21 13:39 UTC, yguclu commented on sympde/topology/mapping.py
> +            expr =  el
After some discussions, we have decided to provide the user with the push-forward expressions used in the code, in order to avoid any confusion. This will be taken care of in a future pull request.

2020-09-21 13:40 UTC, yguclu commented on sympde/topology/mapping.py
> +        This class methods computes the covariant transformation
This is related to the push-forward expressions used in the code, and will be solved with a future pull request.

2020-09-21 13:41 UTC, yguclu approved these changes

2020-09-21 13:43 UTC, merged