Feec multipatch
pyccel/sympde pull request #95
Opened 2021-02-08 08:57 UTC by saidctb

2021-03-08 09:00 UTC, yguclu commented
Can you please provide a general description for this PR, with a detailed list of changes?

2021-03-08 09:13 UTC, yguclu requested changes
As I understand, this PR contains some bug-fixes that are necessary for running vector multi-patch examples in Psydac. But there is no way to know that things are properly working now by looking at this repository alone.

Can you please provide some symbolic unit tests as guarantee of correctness? You should be able to extract them from Psydac! This will ensure that we are not breaking SymPDE in the future.

2021-03-29 10:45 UTC, campospinto commented on sympde/topology/basic.py
> +
this function seems to return either the same boundary edge (in 2D), or the opposite edge. Why is it called `rotate` ?

2021-03-29 10:50 UTC, campospinto commented on sympde/topology/basic.py
> +
the `neighbours` of a domain boundary face (edge in 2D) could easily refer to the domains that are connected across this face. Here the function seems to be returning all the faces that touch self. Maybe 'neighbour_boundaries' or 'adjacent_boundaries' is a better name ?

2021-09-15 15:43 UTC, yguclu commented on sympde/calculus/matrices.py
> +        return '({}).T'.format(sstr(self.arg))
Do we need to add the parentheses if the argument is just a `Matrix`?

2021-09-15 17:07 UTC, saidctb commented on sympde/calculus/matrices.py
> +        return '({}).T'.format(sstr(self.arg))
in the case the argument is just a Matrix, we don't need it, but if it's an expression then yes

2021-09-15 17:38 UTC, yguclu commented on sympde/calculus/matrices.py
> +        return '({}).T'.format(sstr(self.arg))
So maybe we can differentiate between the two cases...?

2021-09-15 17:47 UTC, saidctb commented on sympde/calculus/matrices.py
> +        return '({}).T'.format(sstr(self.arg))
done

2021-09-16 13:30 UTC, yguclu commented on sympde/calculus/matrices.py
> +
It is a bit cleaner to define some lambda functions instead of `f1` and `f2`, don't you think?
```python
Basic._constructor_postprocessor_mapping[MatrixSymbolicExpr] = {
    "Mul": [lambda x: MatSymbolicMul(*x.args)],
    "Add": [lambda x: MatSymbolicAdd(*x.args)],
}
```

2021-09-16 13:33 UTC, saidctb commented on sympde/calculus/matrices.py
> +
done

2021-09-16 14:27 UTC, yguclu commented on sympde/expr/evaluation.py
> +    def __new__(cls, expr, domain, **options):
Please add a docstring to this class... it's very important!

2021-09-16 14:31 UTC, yguclu commented on sympde/expr/evaluation.py
>                          pass
Ehm... why are we ignoring any exception raised by `_get_domain(a)`?

2021-09-16 14:54 UTC, saidctb commented on sympde/expr/evaluation.py
>                          pass
we should maybe delete the try-except clause

2021-09-16 18:49 UTC, yguclu requested changes
These changes look very good to me! I have a few comments

2021-09-16 18:49 UTC, yguclu commented on sympde/topology/mapping.py
> +            return (type(self).__name__, self.mapping)
Is it useful to distinguish between these two cases?

2021-09-16 18:49 UTC, yguclu commented on sympde/calculus/core.py
> +class Trace(BasicOperator):
I don't think it's a good idea to call this new class `Trace`, given that SymPDE already has a `Trace` class in module `sympde.topology.space`... So please change the name of one of these two classes.

2021-09-17 03:40 UTC, saidctb commented on sympde/expr/evaluation.py
> +    def __new__(cls, expr, domain, **options):
done

2021-09-17 04:01 UTC, saidctb commented on sympde/topology/basic.py
> +    def __new__(cls, *boundaries):
it only works, in 2d

2021-09-17 04:02 UTC, saidctb commented on sympde/topology/mapping.py
> +            return (type(self).__name__, self.mapping)
yes, we can have the two cases in one expression, so the hash must be different

2021-09-17 04:02 UTC, saidctb commented on sympde/topology/domain.py
> +    def get_shared_corners(self):
only in 2D

2021-09-17 04:20 UTC, saidctb commented on sympde/calculus/core.py
> +class Trace(BasicOperator):
yes, I shouldn't have added it, we have `SymbolicTrace` for that

2021-09-17 04:21 UTC, saidctb commented on sympde/expr/evaluation.py
> +    Get all scalar trial/test functions in the given expression.
done

2021-09-17 04:21 UTC, saidctb commented on sympde/expr/evaluation.py
> +
done

2021-09-17 04:21 UTC, saidctb commented on sympde/expr/evaluation.py
> +        domain of expr
done

2021-09-17 04:22 UTC, saidctb commented on sympde/calculus/core.py
> +class Trace(BasicOperator):
it's fixed

2021-09-17 04:32 UTC, saidctb commented on sympde/topology/basic.py
> +
In 2d, it's just a 90° rotation, in 3d is more general because we have two directions and not just one

2021-09-17 04:34 UTC, saidctb commented on sympde/topology/basic.py
> +
fixed

2021-09-17 12:19 UTC, yguclu commented on sympde/topology/basic.py
> +
I don't see why it's a 90º rotation in the case that `directions[0] == -1`. It looks like a 180º rotation to me...

2021-09-17 12:21 UTC, yguclu commented on sympde/expr/evaluation.py
>                          pass
Yes please!

2021-09-17 12:22 UTC, yguclu commented on sympde/topology/basic.py
> +    def __new__(cls, *boundaries):
I see. Please expand the docstring to explain it!

2021-09-17 12:23 UTC, yguclu commented on sympde/topology/mapping.py
> +            return (type(self).__name__, self.mapping)
But can't you just use the following in both cases?
```python
return (type(self).__name__, self.mapping, self.axis)
```
The hash will be different if only one of the two cases has `self.axis == None`.

2021-09-17 12:26 UTC, yguclu commented on sympde/calculus/core.py
> +class Trace(BasicOperator):
Should you then update the PR description and remove the line "Add matrix trace operator"?

2021-09-17 12:29 UTC, saidctb commented on sympde/calculus/core.py
> +class Trace(BasicOperator):
yes, I will do it

2021-09-17 12:30 UTC, saidctb commented on sympde/topology/mapping.py
> +            return (type(self).__name__, self.mapping)
it will raise an error, if you include None in the tuple

2021-09-17 12:31 UTC, saidctb commented on sympde/topology/basic.py
> +    def __new__(cls, *boundaries):
this can be generalized to 3d, it's just not implemented , should we still do that ?

2021-09-17 12:34 UTC, yguclu requested changes

2021-09-17 12:34 UTC, yguclu commented on sympde/expr/evaluation.py
> +        """
The constructor's docstrings should be part of the class' docstring, otherwise there is no way to access it from the interpreter...

2021-09-17 12:34 UTC, saidctb commented on sympde/expr/evaluation.py
>                          pass
done

2021-09-17 12:35 UTC, yguclu commented on sympde/topology/mapping.py
> +            return (type(self).__name__, self.mapping)
I thought `None` was hashable...

2021-09-17 12:38 UTC, saidctb commented on sympde/expr/evaluation.py
> +        """
done

2021-09-17 12:38 UTC, yguclu commented on sympde/topology/basic.py
> +    def __new__(cls, *boundaries):
It depends. If you generalized it to 3D, what would it represent? 0D corners or 1D edges?

2021-09-17 12:42 UTC, yguclu requested changes

2021-09-17 12:42 UTC, yguclu commented on sympde/expr/evaluation.py
> +     in a specified domain.
1. vectorized -> vector
2. Sympy -> SymPDE
3. Maybe you wanted to have a single sentence here?

2021-09-17 12:43 UTC, saidctb commented on sympde/topology/basic.py
> +    def __new__(cls, *boundaries):
1D edges

2021-09-17 12:44 UTC, saidctb commented on sympde/topology/mapping.py
> +            return (type(self).__name__, self.mapping)
yes but sympy doesn't like it for some reason

2021-09-17 12:49 UTC, saidctb commented on sympde/expr/evaluation.py
> +     in a specified domain.
ah yes, you are right

2021-09-17 12:51 UTC, saidctb commented on sympde/topology/basic.py
> +
yes my bad 180°

2021-09-17 12:52 UTC, saidctb commented on sympde/expr/evaluation.py
> +     in a specified domain.
fixed

2021-09-17 12:57 UTC, yguclu commented on sympde/topology/mapping.py
> +            return (type(self).__name__, self.mapping)
Never mind then!

2021-09-17 13:15 UTC, yguclu commented on sympde/topology/basic.py
> +    def __new__(cls, *boundaries):
If we want to have it general, we need to decide what it represents in 1D, 2D and 3D. I think that we should have a look at this whole file together with @campospinto

2021-09-17 16:56 UTC, saidctb commented on sympde/topology/basic.py
> +    def __new__(cls, *boundaries):
done

2021-09-17 16:58 UTC, saidctb commented on sympde/topology/domain.py
> +    def get_shared_corners(self):
I have added the docstrings

2021-09-17 19:08 UTC, yguclu approved these changes

2021-09-17 19:11 UTC, merged